package pacote;

import static pacote.Inicio.i;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Gustavo
 */
public class EscolhaClasse extends javax.swing.JFrame {

    /**
     * Creates new form EscolhaClasse
     */
    public EscolhaClasse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jHumanas = new javax.swing.JButton();
        jExatas = new javax.swing.JButton();
        jBiologicas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escolha a profissão que desejas seguir.");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jHumanas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/humanasJuridico.png"))); // NOI18N
        jHumanas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jHumanasMouseMoved(evt);
            }
        });
        jHumanas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHumanasMouseClicked(evt);
            }
        });
        jHumanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHumanasActionPerformed(evt);
            }
        });

        jExatas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/professorutonio2.png"))); // NOI18N
        jExatas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jExatasMouseMoved(evt);
            }
        });
        jExatas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExatasMouseClicked(evt);
            }
        });

        jBiologicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/biologicas.png"))); // NOI18N
        jBiologicas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBiologicasMouseMoved(evt);
            }
        });
        jBiologicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBiologicasMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Humanas");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Exatas");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Biológicas");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBiologicas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jExatas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHumanas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jExatas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jHumanas, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBiologicas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jHumanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHumanasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHumanasActionPerformed

    private void jBiologicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBiologicasMouseClicked
        // TODO add your handling code here:
        Engine.classe = Classe.BIOLOGICAS;
        Inicio inicio = new Inicio();
        i = 9;
        jLabel1.setText(inicio.mudarTexto(i)); //NÃO TÁ ALTERANDO O TEXTO ORIGINAL DA LABEL1
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBiologicasMouseClicked

    private void jExatasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExatasMouseClicked
        // TODO add your handling code here:
        Engine.classe = Classe.EXATAS;
        Inicio inicio = new Inicio();
        i = 9;
        jLabel1.setText(inicio.mudarTexto(i)); //NÃO TÁ ALTERANDO O TEXTO ORIGINAL DA LABEL1
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jExatasMouseClicked

    private void jHumanasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHumanasMouseClicked
        // TODO add your handling code here:
        Engine.classe = Classe.HUMANAS;
        Inicio inicio = new Inicio();
        i = 9;
        jLabel1.setText(inicio.mudarTexto(i)); //NÃO TÁ ALTERANDO O TEXTO ORIGINAL DA LABEL1
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jHumanasMouseClicked

    private void jHumanasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHumanasMouseMoved
        // TODO add your handling code here:
        jLabel1.setText("Fracasse vendendo sua arte na praia.");
    }//GEN-LAST:event_jHumanasMouseMoved

    private void jExatasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExatasMouseMoved
        // TODO add your handling code here:
        jLabel1.setText("Fracasse aprendendo a contar o troco.");
    }//GEN-LAST:event_jExatasMouseMoved

    private void jBiologicasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBiologicasMouseMoved
        // TODO add your handling code here:
        jLabel1.setText("Fracasse e dê a injeção errada nos pacientes.");
    }//GEN-LAST:event_jBiologicasMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaClasse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBiologicas;
    private javax.swing.JButton jExatas;
    private javax.swing.JButton jHumanas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
