package pacote;

import java.awt.Font;
import static java.awt.PageAttributes.MediaType.C;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import pacote.EscolhaSexo;


public class Inicio extends javax.swing.JFrame {

    public static String c;
    public static int i = 0;
   
    
    
    
    public Inicio() {
        initComponents();
        
    }

    public void close(){
        WindowEvent ev = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(ev);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("Clique para começar.");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jButton.setForeground(new java.awt.Color(204, 204, 204));
        jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Spr_HGSS_Oak.png"))); // NOI18N
        jButton.setText("OAK");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formKeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jLabel1.setText(mudarTexto(i));
        i++;
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActionPerformed

    
    public String mudarTexto(int i){
            //jTexto.setText("Olá,bem vindo ao mundo pokémon");
             //int i = 0;
    switch(i){
    case 0:
        c ="Olá,seja bem vindo(a) à Universidade !";
        break;
    case 1:
        ImageIcon imagem;
        imagem = new ImageIcon(getClass().getResource("oak.png"));
        jButton.setIcon(imagem);
        c  =  "Eu serei seu mentor e o ajudarei na sua jornada estudantil.";
        break;
    case 2:
        System.out.println("primeiro,preciso saber...");
        c = "primeiro,preciso saber...";
        break;
    case 3:
        EscolhaSexo frame2 = new EscolhaSexo();
        frame2.setVisible(true);
        hide();
        //dispose();
        c = "Você é garoto ou garota?";
        break;
    case 4:
        if(Engine.s == Sexo.GAROTO)
        c = "Hmmmm....Interessante...Um fracassado em potencial.";
        else if(Engine.s == Sexo.GAROTA)
        c = "Hmmmm....Interessante...Uma fracassada em potencial."; 
        break;  
    case 5:
        EscolherNome frame3 = new EscolherNome();
        frame3.setVisible(true);
        hide();
        break;
    case 6:
        if("Gustavo".equals(Engine.nome) || "Victor".equals(Engine.nome) || "Ariel".equals(Engine.nome)){
            c = ("OK, " + Engine.nome + ", um belo nome!");
        }else if("".equals(Engine.nome)){
            c = "Não tem nome? Sem problemas,vou chamá-lo de Fracassildo!";
            Engine.nome = "Fracassildo";
        }
        else
            c = "Hmmm..."+Engine.nome+"...Que nome sem graça.";
        break;
    case 7:
        c = "Vamos lá, agora preciso saber...";
        break;
    case 8:
        EscolhaClasse frame4 = new EscolhaClasse();
        frame4.setVisible(true);
        hide();
        break;
    case 9:
        if(Engine.classe == Classe.EXATAS)
            c = (Engine.classe + "...Sábia escolha.");
        else if(Engine.classe == Classe.HUMANAS)
            c = (Engine.classe  + "...Uau,espero que tenha feito PROERD.");   
        else if(Engine.classe == Classe.BIOLOGICAS)
            c = (Engine.classe + "...Hmm,coitado dos animaizinhos.");
        break;
    case 10:
        c = "Okay,okay,o tempo passa, e a hora de fracassar chegou.";
        break;
    case 11:
        c = "Está pronto para acessar a Universidade?";
        //TELA DE DECISAO
        break;
    case 12:
        c = "Certo, agora começa uma nova etapa na sua vida";
        break;
    case 13:
        c = "Não estranhe se a fonte do jogo mudar,";
        break;
    case 14:  
        Font font = new Font("Arial", Font.PLAIN, 11);
        //jLabel1.setDefaultFont(font);
        jLabel1.setFont(font);
        c = "O programador preguiçoso só teve essa ideia agora";
      break;  
    case 15:
        Font f = new Font("Orange Juice", Font.PLAIN, 35);
        jLabel1.setFont(f);
        c = "Boa Sorte!";
        break;
    default:
        break;
}

        return c;
    }
   
    
    
    public static void main(String args[]) {
        // Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //new Inicio().setVisible(true);
                Inicio inicio = new Inicio();
                inicio.setVisible(true);
                
                
            }
        });
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    


}
